# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rimac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rimac
pod 'Alamofire'
  target 'RimacTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RimacUITests' do
    # Pods for testing
  end

end
